'use client';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Link from 'next/link';
import { useAuth } from '@/lib/AuthContext';
import Sidebar from '@/components/Sidebar';

export default function Reports() {
  const { user } = useAuth();

  const recentReports = [
    { id: "REP-2024-001", date: "Oct 24, 2024", site: "nexusdata.io", score: 72, status: "Critical Issues", type: "Full behavioral audit" },
    { id: "REP-2024-002", date: "Oct 22, 2024", site: "nexusdata.io/pricing", score: 84, status: "Optimized", type: "Funnel leak analysis" },
    { id: "REP-2024-003", date: "Oct 15, 2024", site: "nexusdata.io/blog", score: 61, status: "High Friction", type: "Trust signal audit" }
  ];

  return (
    <div className="flex flex-col min-h-screen bg-background antialiased selection:bg-secondary selection:text-on-secondary">
      <Navbar />

      <main className="flex-grow w-full max-w-container-max mx-auto px-4 md:px-gutter py-8 md:py-xl pt-24 lg:pt-32 grid grid-cols-1 lg:grid-cols-12 gap-gutter">
        <Sidebar />

        <div className="lg:col-span-9 flex flex-col gap-lg">
          <header className="flex flex-col md:flex-row md:items-end justify-between gap-6">
            <div>
              <div className="flex items-center gap-2 text-secondary font-label-mono text-label-mono uppercase tracking-widest mb-2">
                <span className="material-symbols-outlined text-[18px]">assessment</span>
                Analysis
              </div>
              <h1 className="font-display-xl text-display-xl text-primary tracking-tight">
                Automated Reports
              </h1>
              <p className="font-body-md text-on-surface-variant max-w-2xl mt-2 leading-relaxed">
                Historical performance data and detailed behavioral analysis generated by your AI swarm.
              </p>
            </div>
            <button className="bg-primary text-on-primary px-6 py-3 rounded-xl font-bold flex items-center gap-2 hover:opacity-90 shadow-lg transition-all active:scale-95">
              <span className="material-symbols-outlined">add</span>
              Generate New Report
            </button>
          </header>

          {/* Report Stats */}
          <section className="grid grid-cols-1 md:grid-cols-4 gap-md">
            {[
              { label: "Total Reports", value: "156", icon: "summarize", color: "text-primary" },
              { label: "Avg. Score", value: "74%", icon: "speed", color: "text-secondary" },
              { label: "Critical Leaks", value: "12", icon: "warning", color: "text-error" },
              { label: "Resolved", value: "89", icon: "check_circle", color: "text-tertiary-fixed-dim" }
            ].map((stat, i) => (
              <div key={i} className="bg-surface-container-lowest border border-outline-variant p-md rounded-2xl shadow-sm flex flex-col gap-2">
                <div className="flex items-center justify-between">
                  <span className="font-label-mono text-label-mono text-on-surface-variant uppercase tracking-wider">{stat.label}</span>
                  <span className={`material-symbols-outlined ${stat.color}`}>{stat.icon}</span>
                </div>
                <div className={`font-headline-lg text-headline-lg ${stat.color}`}>{stat.value}</div>
              </div>
            ))}
          </section>

          <div className="relative">
            {(!user || !user.isPro) && (
              <div className="absolute inset-0 z-20 bg-background/40 backdrop-blur-md flex flex-col items-center justify-center p-6 text-center rounded-2xl">
                <div className="bg-surface-container-lowest p-8 rounded-2xl border border-outline-variant shadow-2xl max-w-md">
                  <span className="material-symbols-outlined text-4xl text-secondary mb-4">lock</span>
                  <h3 className="font-headline-md text-primary mb-2">Historical Reports Locked</h3>
                  <p className="font-body-sm text-on-surface-variant mb-6">
                    {!user 
                      ? "Create a free account or sign in to access your full history of automated swarm reports." 
                      : "Upgrade to the Pro plan to access your full history of automated swarm reports."}
                  </p>
                  <div className="flex gap-4 justify-center">
                    {!user ? (
                      <>
                        <Link href="/login" className="px-6 py-2 border border-outline-variant rounded-xl font-bold text-sm hover:bg-surface-container-low transition-colors">Sign In</Link>
                        <Link href="/register" className="px-6 py-2 bg-primary text-on-primary rounded-xl font-bold text-sm hover:opacity-90 transition-opacity">Get Started</Link>
                      </>
                    ) : (
                      <Link href="/upgrade" className="px-6 py-2 bg-secondary text-on-secondary rounded-xl font-bold text-sm hover:opacity-90 transition-opacity">Upgrade to Pro</Link>
                    )}
                  </div>
                </div>
              </div>
            )}

            
            {/* Reports Table */}
            <section className="bg-surface-container-lowest border border-outline-variant rounded-2xl shadow-xl overflow-hidden">
              <div className="p-md bg-surface-container-low/30 border-b border-outline-variant flex items-center justify-between">
                <h2 className="font-headline-md text-headline-md text-on-surface">Recent Analysis</h2>
                <div className="relative">
                  <span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-on-surface-variant text-sm">search</span>
                  <input type="text" placeholder="Filter reports..." className="pl-10 pr-4 py-2 rounded-lg border border-outline-variant bg-white text-sm focus:outline-none focus:border-secondary transition-all" />
                </div>
              </div>
              
              <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse">
                  <thead>
                    <tr className="bg-surface-container-low/50 border-b border-outline-variant font-label-mono text-[11px] text-on-surface-variant uppercase tracking-widest">
                      <th className="px-lg py-md">Report ID</th>
                      <th className="px-lg py-md">Target URL</th>
                      <th className="px-lg py-md">Analysis Date</th>
                      <th className="px-lg py-md">Score</th>
                      <th className="px-lg py-md">Status</th>
                      <th className="px-lg py-md text-right">Action</th>
                    </tr>
                  </thead>
                  <tbody className="font-body-md text-body-md text-on-surface">
                    {recentReports.map((report, i) => (
                      <tr key={i} className="border-b border-outline-variant/30 hover:bg-surface-container-low/20 transition-colors group">
                        <td className="px-lg py-md font-mono text-xs">{report.id}</td>
                        <td className="px-lg py-md font-medium text-secondary">{report.site}</td>
                        <td className="px-lg py-md text-on-surface-variant">{report.date}</td>
                        <td className="px-lg py-md">
                          <div className="flex items-center gap-2">
                            <div className="w-8 h-8 rounded-full border-2 border-outline-variant flex items-center justify-center text-xs font-bold">
                              {report.score}
                            </div>
                            <div className="flex-grow w-16 bg-surface-container h-1 rounded-full overflow-hidden">
                              <div className={`h-full rounded-full ${report.score > 80 ? 'bg-secondary' : 'bg-error'}`} style={{ width: `${report.score}%` }}></div>
                            </div>
                          </div>
                        </td>
                        <td className="px-lg py-md">
                          <span className={`px-2 py-1 rounded-full text-[10px] font-bold uppercase tracking-tighter border ${
                            report.status === 'Optimized' ? 'bg-secondary/10 text-secondary border-secondary/20' : 'bg-error/10 text-error border-error/20'
                          }`}>
                            {report.status}
                          </span>
                        </td>
                        <td className="px-lg py-md text-right">
                          <button className="text-secondary hover:text-primary transition-colors flex items-center gap-1 ml-auto font-semibold">
                            View <span className="material-symbols-outlined text-[18px] group-hover:translate-x-1 transition-transform">chevron_right</span>
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </section>

            {/* Empty State Mock */}
            <div className="p-xl text-center flex flex-col items-center gap-md border-2 border-dashed border-outline-variant rounded-2xl opacity-60 mt-xl">
              <span className="material-symbols-outlined text-5xl text-outline-variant">folder_open</span>
              <div className="max-w-sm">
                <h3 className="font-headline-md text-on-surface mb-xs">No archived reports</h3>
                <p className="font-body-sm text-on-surface-variant">Your older reports are being processed and will appear here shortly.</p>
              </div>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
