'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Link from 'next/link';
import { useAuth } from '@/lib/AuthContext';
import Sidebar from '@/components/Sidebar';

// Shared score banding: >=80 healthy, >=60 at-risk, else critical.
function scoreBand(score: number) {
  if (score >= 80) return { label: 'Healthy', bar: 'bg-emerald-500', ring: 'border-emerald-500 text-emerald-600' };
  if (score >= 60) return { label: 'At Risk', bar: 'bg-amber-500', ring: 'border-amber-500 text-amber-600' };
  return { label: 'Critical', bar: 'bg-error', ring: 'border-error text-error' };
}

export default function Reports() {
  const router = useRouter();
  const { user, isLoading } = useAuth();
  const [query, setQuery] = useState('');

  // Redirect to login if not authenticated
  useEffect(() => {
    if (!isLoading && !user) {
      router.push('/login');
    }
  }, [user, isLoading, router]);

  const recentReports = [
    { id: "REP-2024-001", date: "Oct 24, 2024", site: "nexusdata.io", score: 72, status: "Critical Issues", type: "Full behavioral audit" },
    { id: "REP-2024-002", date: "Oct 22, 2024", site: "nexusdata.io/pricing", score: 84, status: "Optimized", type: "Funnel leak analysis" },
    { id: "REP-2024-003", date: "Oct 15, 2024", site: "nexusdata.io/blog", score: 61, status: "High Friction", type: "Trust signal audit" }
  ];

  if (isLoading) {
    return (
      <div className="min-h-screen bg-slate-950 flex flex-col items-center justify-center">
        <div className="w-20 h-20 border-2 border-primary/20 rounded-full"></div>
        <div className="w-20 h-20 border-t-2 border-primary rounded-full animate-spin absolute"></div>
      </div>
    );
  }

  if (!user) {
    return null; // redirecting
  }

  const isPro = user.isPro === true;

  // Wire the "Filter reports…" box: match against id, site, status, or type.
  const q = query.trim().toLowerCase();
  const filtered = q
    ? recentReports.filter((r) =>
        [r.id, r.site, r.status, r.type].some((f) => f.toLowerCase().includes(q))
      )
    : recentReports;

  return (
    <div className="flex flex-col min-h-screen bg-background antialiased selection:bg-secondary selection:text-on-secondary">
      <Navbar />

      <main className="flex-grow w-full max-w-container-max mx-auto px-4 md:px-gutter py-8 md:py-xl pt-24 lg:pt-32 grid grid-cols-1 lg:grid-cols-12 gap-gutter">
        <Sidebar />

        <div className="lg:col-span-9 flex flex-col gap-lg">
          <header className="flex flex-col md:flex-row md:items-end justify-between gap-6">
            <div>
              <div className="flex items-center gap-2 text-secondary font-label-mono text-label-mono uppercase tracking-widest mb-2 font-bold">
                <span className="material-symbols-outlined text-[18px]">assessment</span>
                Analysis
              </div>
              <h1 className="font-display-xl text-display-xl text-primary tracking-tight font-black">
                Automated Reports
              </h1>
              <p className="font-body-md text-on-surface-variant max-w-2xl mt-2 leading-relaxed font-sans text-sm">
                Historical performance data and detailed behavioral analysis generated by your AI swarm.
              </p>
            </div>
            <button
              onClick={() => router.push(isPro ? '/' : '/checkout')}
              className="bg-primary text-on-primary px-6 py-3 rounded-none font-bold flex items-center gap-2 hover:opacity-90 shadow-lg transition-all active:scale-95 text-xs uppercase tracking-widest"
            >
              <span className="material-symbols-outlined text-sm">add</span>
              Generate New Report
            </button>
          </header>

          {/* Report Stats */}
          <section className="grid grid-cols-1 md:grid-cols-4 gap-md">
            {[
              { label: "Total Reports", value: "156", icon: "summarize", color: "text-primary" },
              { label: "Avg. Score", value: "74%", icon: "speed", color: "text-secondary" },
              { label: "Critical Leaks", value: "12", icon: "warning", color: "text-error" },
              { label: "Resolved", value: "89", icon: "check_circle", color: "text-emerald-600" }
            ].map((stat, i) => (
              <div key={i} className="bg-surface-container-lowest border border-outline-variant p-md rounded-none shadow-sm flex flex-col gap-2">
                <div className="flex items-center justify-between">
                  <span className="font-label-mono text-[9px] text-on-surface-variant uppercase tracking-wider font-bold">{stat.label}</span>
                  <span className={`material-symbols-outlined ${stat.color}`}>{stat.icon}</span>
                </div>
                <div className={`font-headline-lg text-3xl font-extrabold ${stat.color}`}>{stat.value}</div>
              </div>
            ))}
          </section>

          <div className="relative">
            {!isPro && (
              <div className="absolute inset-0 z-20 bg-background/50 backdrop-blur-md flex flex-col items-center justify-center p-6 text-center rounded-none">
                <div className="bg-surface-container-lowest p-8 rounded-none border border-outline-variant shadow-2xl max-w-md">
                  <span className="material-symbols-outlined text-4xl text-secondary mb-4">lock</span>
                  <h3 className="font-headline-md text-primary mb-2 font-bold">Historical Reports Locked</h3>
                  <p className="font-body-sm text-on-surface-variant mb-6 font-sans text-xs leading-relaxed">
                    Upgrade to the Pro plan to access and browse your full history of automated swarm reports.
                  </p>
                  <div className="flex gap-4 justify-center">
                    <Link href="/checkout" className="px-6 py-3 bg-secondary text-on-secondary rounded-none font-bold text-xs uppercase tracking-widest hover:opacity-90 transition-opacity">Upgrade to Pro ($29)</Link>
                  </div>
                </div>
              </div>
            )}

            {/* Reports Table */}
            <section className="bg-surface-container-lowest border border-outline-variant rounded-none shadow-xl overflow-hidden">
              <div className="p-md bg-surface-container-low/30 border-b border-outline-variant flex items-center justify-between">
                <h2 className="font-headline-md text-headline-md text-on-surface font-bold text-lg">Recent Analysis</h2>
                <div className="relative">
                  <span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-on-surface-variant text-sm">search</span>
                  <input
                    type="text"
                    value={query}
                    onChange={(e) => setQuery(e.target.value)}
                    placeholder="Filter reports..."
                    className="pl-10 pr-4 py-2 rounded-none border border-outline-variant bg-white text-sm focus:outline-none focus:border-secondary transition-all"
                  />
                </div>
              </div>
              
              <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse">
                  <thead>
                    <tr className="bg-surface-container-low/50 border-b border-outline-variant font-label-mono text-[10px] text-on-surface-variant uppercase tracking-widest font-bold">
                      <th className="px-lg py-md">Report ID</th>
                      <th className="px-lg py-md">Target URL</th>
                      <th className="px-lg py-md">Analysis Date</th>
                      <th className="px-lg py-md">Score</th>
                      <th className="px-lg py-md">Status</th>
                      <th className="px-lg py-md text-right">Action</th>
                    </tr>
                  </thead>
                  <tbody className="font-body-md text-body-md text-on-surface">
                    {filtered.length === 0 && (
                      <tr>
                        <td colSpan={6} className="px-lg py-xl text-center text-on-surface-variant font-sans text-sm">
                          No reports match &ldquo;{query}&rdquo;.
                        </td>
                      </tr>
                    )}
                    {filtered.map((report, i) => {
                      const band = scoreBand(report.score);
                      return (
                      <tr key={i} className="border-b border-outline-variant/30 hover:bg-surface-container-low/20 transition-colors group">
                        <td className="px-lg py-md font-mono text-xs">{report.id}</td>
                        <td className="px-lg py-md font-medium text-secondary">{report.site}</td>
                        <td className="px-lg py-md text-on-surface-variant">{report.date}</td>
                        <td className="px-lg py-md">
                          <div className="flex items-center gap-2">
                            <div className={`w-8 h-8 rounded-full border-2 flex items-center justify-center text-xs font-bold ${band.ring}`}>
                              {report.score}
                            </div>
                            <div className="flex-grow w-16 bg-surface-container h-1 overflow-hidden rounded-none">
                              <div className={`h-full ${band.bar}`} style={{ width: `${report.score}%` }}></div>
                            </div>
                          </div>
                        </td>
                        <td className="px-lg py-md">
                          <span className={`px-2 py-1 rounded-none text-[10px] font-bold uppercase tracking-tighter border ${
                            report.status === 'Optimized' ? 'bg-secondary/10 text-secondary border-secondary/20' : 'bg-error/10 text-error border-error/20'
                          }`}>
                            {report.status}
                          </span>
                        </td>
                        <td className="px-lg py-md text-right">
                          <button className="text-secondary hover:text-primary transition-colors flex items-center gap-1 ml-auto font-semibold text-xs uppercase tracking-widest">
                            View <span className="material-symbols-outlined text-[18px] group-hover:translate-x-1 transition-transform">chevron_right</span>
                          </button>
                        </td>
                      </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </section>

            {/* Empty State — only when there are genuinely no archived reports */}
            {recentReports.length === 0 && (
              <div className="p-xl text-center flex flex-col items-center gap-md border-2 border-dashed border-outline-variant rounded-none opacity-60 mt-xl">
                <span className="material-symbols-outlined text-5xl text-outline-variant">folder_open</span>
                <div className="max-w-sm">
                  <h3 className="font-headline-md text-on-surface mb-xs font-bold text-lg">No archived reports</h3>
                  <p className="font-body-sm text-on-surface-variant font-sans text-xs">Run your first scan and it will appear here.</p>
                </div>
              </div>
            )}
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
