import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

export default function Legal() {
  const sections = [
    {
      id: "license",
      icon: "gavel",
      title: "Software License Agreement",
      content: [
        "Subject to the terms and conditions of this Agreement, Horizons AI grants you a limited, non-exclusive, non-transferable, and revocable license to access and use the Platform strictly in accordance with your chosen subscription tier. This license does not permit any resale, sublicensing, or commercial exploitation of the Platform's core algorithms or underlying infrastructure.",
        "You acknowledge that the Platform, including all intellectual property rights therein, remains the exclusive property of Horizons AI. No rights are granted to you other than as expressly set forth herein. You shall not attempt to reverse engineer, decompile, or extract the source code of the Platform or any part thereof, unless expressly permitted or required by law."
      ],
      subSection: {
        title: "Usage Rights",
        text: "Authorized users may utilize the predictive modeling and analytics outputs generated by the Platform for internal business purposes. External distribution of raw model outputs requires prior written consent from Horizons AI legal representation."
      }
    },
    {
      id: "privacy",
      icon: "shield_lock",
      title: "Data Privacy Policy",
      content: [
        "Horizons AI is committed to maintaining the highest standards of data integrity and security. We process customer data exclusively for the purpose of providing, maintaining, and improving the Platform's core functionalities.",
        "All data ingested into the Horizons ecosystem is encrypted in transit using TLS 1.3 and at rest using AES-256 encryption. We adhere strictly to SOC 2 Type II compliance standards and undergo regular third-party audits to ensure our security posture remains robust against emerging threat vectors."
      ],
      list: [
        "Data Minimization: We only collect data necessary for algorithmic performance.",
        "Tenant Isolation: Customer data is logically segregated to prevent cross-contamination.",
        "Retention Policies: Data is retained only for the active lifecycle of the subscription plus 30 days."
      ]
    },
    {
      id: "terms",
      icon: "description",
      title: "Terms of Service",
      content: [
        "By accessing or using the Horizons AI Platform, you agree to be bound by these Terms of Service. If you do not agree to all the terms and conditions, you are prohibited from accessing the platform.",
        "You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to immediately notify Horizons AI of any unauthorized use of your account or any other breaches of security.",
        "We reserve the right to suspend or terminate your access to the Platform at any time, without notice or liability, for any reason, including if you breach these Terms. Upon termination, your right to use the Platform will immediately cease."
      ]
    }
  ];

  return (
    <div className="flex flex-col min-h-screen bg-background">
      <Navbar />

      <main className="w-full max-w-[800px] mx-auto px-gutter py-xl pt-[140px] flex flex-col gap-xl">
        {/* Page Header */}
        <header className="text-center flex flex-col gap-md">
          <p className="font-label-mono text-label-mono text-primary-container uppercase tracking-widest">Legal Information</p>
          <h1 className="font-display-xl text-display-xl text-primary">Agreements & Policies</h1>
          <p className="font-body-lg text-body-lg text-on-surface-variant max-w-2xl mx-auto leading-relaxed">
            These documents dictate the parameters of use, data handling protocols, and operational licensing for the Horizons AI platform. Last updated on October 24, 2024.
          </p>
        </header>

        <div className="h-px w-full bg-gradient-to-r from-transparent via-outline-variant/50 to-transparent"></div>

        {/* Navigation Links */}
        <nav className="flex items-center justify-center gap-lg overflow-x-auto no-scrollbar py-sm border-b border-outline-variant/20 sticky top-[72px] bg-background/80 backdrop-blur-md z-30">
          {sections.map((s) => (
            <a key={s.id} href={`#${s.id}`} className="font-label-mono text-label-mono text-on-surface-variant hover:text-secondary transition-colors uppercase tracking-wider">
              {s.title.split(' ')[0]}
            </a>
          ))}
        </nav>

        {/* Legal Sections */}
        <div className="flex flex-col gap-xl">
          {sections.map((section) => (
            <section key={section.id} id={section.id} className="flex flex-col gap-lg scroll-mt-32">
              <div className="flex items-center gap-sm">
                <span className="material-symbols-outlined text-secondary text-3xl" style={{ fontVariationSettings: "'FILL' 1" }}>
                  {section.icon}
                </span>
                <h2 className="font-headline-lg text-headline-lg text-primary">{section.title}</h2>
              </div>

              <div className="flex flex-col gap-md font-body-md text-body-md text-on-surface-variant leading-relaxed">
                {section.content.map((p, i) => (
                  <p key={i}>{p}</p>
                ))}

                {section.subSection && (
                  <div className="bg-surface-container-low p-md rounded-xl border border-outline-variant/50 mt-sm">
                    <h3 className="font-headline-md text-headline-md text-on-surface mb-xs">{section.subSection.title}</h3>
                    <p className="font-body-sm text-body-sm text-on-surface-variant">{section.subSection.text}</p>
                  </div>
                )}

                {section.list && (
                  <ul className="list-disc pl-lg flex flex-col gap-xs mt-sm">
                    {section.list.map((item, i) => (
                      <li key={i} className="font-medium text-on-surface">{item}</li>
                    ))}
                  </ul>
                )}
              </div>
            </section>
          ))}
        </div>

        {/* Contact Support CTA */}
        <div className="mt-xl p-lg rounded-xl bg-surface-container-high border border-outline-variant flex flex-col md:flex-row items-center justify-between gap-md">
          <div className="flex flex-col gap-1">
            <h4 className="font-headline-md text-headline-md text-primary">Have legal questions?</h4>
            <p className="font-body-sm text-on-surface-variant">Contact our legal team for compliance inquiries.</p>
          </div>
          <button className="bg-primary text-on-primary px-6 py-2 rounded-lg font-bold hover:opacity-90 transition-opacity">
            Contact Legal
          </button>
        </div>
      </main>

      <Footer />
    </div>
  );
}
